// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacional.Financeiro.Data;

#nullable disable

namespace PlataformaEducacional.Financeiro.Data.Migrations
{
    [DbContext(typeof(FinanceiroContext))]
    [Migration("20250604222238_PrimeiroMigration")]
    partial class PrimeiroMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PlataformaEducacional.Financeiro.Domain.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pagamento", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.Financeiro.Domain.Pagamento", b =>
                {
                    b.OwnsOne("PlataformaEducacional.Financeiro.Domain.DadosCartao", "DadosCartao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CvvCartao")
                                .IsRequired()
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("NomeTitular")
                                .IsRequired()
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("NumeroMascarado")
                                .IsRequired()
                                .HasColumnType("varchar(100)");

                            b1.Property<DateTime>("Validade")
                                .HasColumnType("TEXT");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamento");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.OwnsOne("PlataformaEducacional.Financeiro.Domain.StatusPagamento", "Status", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MotivoRejeicao")
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("varchar(100)");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamento");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.Navigation("DadosCartao")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
