// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacional.Conteudo.Data;

#nullable disable

namespace PlataformaEducacional.Conteudo.Data.Migrations
{
    [DbContext(typeof(ConteudoContext))]
    partial class ConteudoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PlataformaEducacional.Conteudo.Domain.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Aula", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.Conteudo.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Curso", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacional.Conteudo.Domain.Aula", b =>
                {
                    b.HasOne("PlataformaEducacional.Conteudo.Domain.Curso", "Curso")
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("PlataformaEducacional.Conteudo.Domain.Curso", b =>
                {
                    b.OwnsOne("PlataformaEducacional.Conteudo.Domain.ConteudoProgramatico", "Conteudo", b1 =>
                        {
                            b1.Property<Guid>("CursoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CargaHoraria")
                                .IsRequired()
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("MaterialComplementarUrl")
                                .IsRequired()
                                .HasColumnType("varchar(100)");

                            b1.HasKey("CursoId");

                            b1.ToTable("Curso");

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.Navigation("Conteudo")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEducacional.Conteudo.Domain.Curso", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
